pipeline {
    agent { label 'AGENT-1' }
    environment { 
        PROJECT = 'expense'
        COMPONENT = 'backend'
        appVersion = '' 
        ACC_ID = '724772064412'
    }
    options {
        disableConcurrentBuilds()
        timeout(time: 30, unit: 'MINUTES')
        ansiColor('xterm')
    }
    stages {
        stage('Init') {
            steps {
               script{
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                 sh """
                    cd 10-sg
                    terraform init -reconfigure
                    terraform plan
                """
                }
               }
            }
        }
        stage('Apply'){
            input {
                message "Should we continue?"
                ok "Yes, we should."
            }
            steps{
                script{
                    withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 10-sg
                        terraform apply -auto-approve
                    """
                    }
                }
            }
            
        }
    }
    post { 
        always { 
            echo 'I will always say Hello again!'
            deleteDir()
        }
        failure { 
            echo 'I will run when pipeline is failed'
        }
        success { 
            echo 'I will run when pipeline is success'
        }
    }
}